---
title: "Beer_Brew_ analysis"
author: "Steven Hayden, Thejas Prasad"
date: "October 10, 2017"
output: 
  html_document:
    keep_md: true
---

install.packages("sqldf")
library("sqldf")
```{r echo=TRUE}
install.packages("data.table")
library("data.table")
```

Report the number of NA's in each column.
```{r echo=TRUE}
#3

colSums(is.na(beer_brew_merge))

```


Compute the median alcohol content and international bitterness unit for each state. 
```{r echo=TRUE}


# 4. 
#Uses SQL to group data by state (like the tapply functtion) and provied the Median ABV and Median IBU
ABV_IBU_Median = (sqldf("SELECT median(ABV) as ABV_Median,median(IBU) as IBU_Median, State FROM beer_brew_merge GROUP By State"))




par(mar=c(5, 3, 4.1, 0), mgp=c(3, 1, 0), las=2)
barplot( ABV_IBU_Median$ABV_Median,col=c("darkblue"),space = 1,
     main="ABV Median vs State", # Title
     xlab="ABV Median" ,         # xaxis label 
     names.arg = ABV_IBU_Median$State) 

barplot( ABV_IBU_Median$IBU_Median,col=c("red"),space = 1,
         main="IBU Median vs State", # Title
         xlab="IBU Median",          # xaxis label 
         names.arg = ABV_IBU_Median$State)






#par(les=2) 
par(mar=c(5.1, 17, 4.1, 2.1), mgp=c(15, 1, 0), las=2)
barplot(major_count,length(major_count),horiz = TRUE, main = "count of majors by category",xlab = "Count",ylab = "Category",col = c("lightblue", "mistyrose", "lightcyan",
                "lavender", "cornsilk"))
```


 
Which state has the maximum alcoholic (ABV) beer? 
```{r echo=TRUE}
# 5. 
#Finds the max ABV and the state Associated with it
beer_brew_merge[which(beer_brew_merge$ABV==max(beer_brew_merge$ABV,na.rm = TRUE)),"State"]

```


Which state has the most bitter (IBU) beer?
```{r echo=TRUE}
#Alternitive methode

bbm = data.table(beer_brew_merge)

max_ibu = max(bbm[, IBU], na.rm = TRUE)

bbm[IBU == max_ibu, .(State, IBU)]
```




Summary statistics for the ABV variable
```{r echo=TRUE}
# 6. Summary statistics for the ABV variable
summary(beer_brew_merge$ABV, na.rm = TRUE)
```



```{r echo=TRUE}

# 7. Is there an apparent relationship between the bitterness of the beer and its alcoholic
# content? Draw a scatter plot.
# You are welcome to use the ggplot2 library for graphs. Please ignore missing values in
# your analysis. Make your best judgment of a relationship and EXPLAIN your answer.



#import data


# Data Frame -> Low = 1, Low-Medium = 2, Medium-High = 3, High = 4

df1 = data.frame(beer_brew_merge, na.rm = TRUE)


#Linear reg

regressor = lm(formula = IBU ~ ABV, data=df1 )


#predict
y_pred = predict(regressor, newdata = df1 )


#ggplot
install.packages("ggplot2",dependencies = TRUE)
library(ggplot2)
#install.packages("gtable")
#library(gtable)
#install.packages("labeling")
#library(labeling)


ggplot() +
  geom_point(aes(x= df1$ABV, y= df1$IBU),
             colour='red', na.rm = TRUE,size = .75)+
  geom_line(aes(x= df1$ABV,y= predict(regressor, newdata = df1 )),
            colour='blue',na.rm = TRUE)+
  ggtitle('ABV vs IBU')+
  xlab('ABV')+
  ylab('IBU')

?ggplot

# Yes there is a linear correlation between alcholol content and the bitterness of the beer
# as the alcholol content increases and the bitterness of the beer also increases.

#----Done---

```
